{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-GB",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/localhost;PricesPaid",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "localhost",
            "database": "PricesPaid"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "BusinessDate",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "Sale Date",
            "dataType": "string",
            "sourceColumn": "Sale Date"
          },
          {
            "name": "Date Sort",
            "dataType": "int64",
            "sourceColumn": "Date Sort"
          },
          {
            "name": "Sale Month",
            "dataType": "string",
            "sourceColumn": "Sale Month"
          },
          {
            "name": "Sale Year",
            "dataType": "int64",
            "sourceColumn": "Sale Year"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;PricesPaid\",",
                "    dbo_BusinessDate = Source{[Schema=\"dbo\",Item=\"BusinessDate\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_BusinessDate,{{\"Date Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Location",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "Postcode",
            "dataType": "string",
            "sourceColumn": "Postcode"
          },
          {
            "name": "Locality",
            "dataType": "string",
            "sourceColumn": "Locality"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;PricesPaid\",",
                "    dbo_Location = Source{[Schema=\"dbo\",Item=\"Location\"]}[Data],",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(dbo_Location,{{\"Locality\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ]
      },
      {
        "name": "NewBuild",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "Is New Build",
            "dataType": "string",
            "sourceColumn": "Is New Build"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;PricesPaid\",",
                "    dbo_NewBuild = Source{[Schema=\"dbo\",Item=\"NewBuild\"]}[Data]",
                "in",
                "    dbo_NewBuild"
              ]
            }
          }
        ]
      },
      {
        "name": "PropertyAddress",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "Postcode",
            "dataType": "string",
            "sourceColumn": "Postcode"
          },
          {
            "name": "Town",
            "dataType": "string",
            "sourceColumn": "Town"
          },
          {
            "name": "District",
            "dataType": "string",
            "sourceColumn": "District"
          },
          {
            "name": "County",
            "dataType": "string",
            "sourceColumn": "County"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;PricesPaid\",",
                "    dbo_PropertyAddress = Source{[Schema=\"dbo\",Item=\"PropertyAddress\"]}[Data],",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(dbo_PropertyAddress,{{\"Address\", Text.Proper, type text}, {\"Town\", Text.Proper, type text}, {\"District\", Text.Proper, type text}, {\"County\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ]
      },
      {
        "name": "LandOwnership",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "Land Use Type",
            "dataType": "string",
            "sourceColumn": "Land Use Type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;PricesPaid\",",
                "    dbo_LandOwnership = Source{[Schema=\"dbo\",Item=\"LandOwnership\"]}[Data]",
                "in",
                "    dbo_LandOwnership"
              ]
            }
          }
        ]
      },
      {
        "name": "Prices",
        "columns": [
          {
            "name": "Business Date ID",
            "dataType": "int64",
            "sourceColumn": "Business Date ID"
          },
          {
            "name": "Location ID",
            "dataType": "int64",
            "sourceColumn": "Location ID"
          },
          {
            "name": "Address ID",
            "dataType": "int64",
            "sourceColumn": "Address ID"
          },
          {
            "name": "Property Type ID",
            "dataType": "int64",
            "sourceColumn": "Property Type ID"
          },
          {
            "name": "Land Ownership ID",
            "dataType": "int64",
            "sourceColumn": "Land Ownership ID"
          },
          {
            "name": "New Build ID",
            "dataType": "int64",
            "sourceColumn": "New Build ID"
          },
          {
            "name": "Price",
            "dataType": "decimal",
            "sourceColumn": "Price"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;PricesPaid\",",
                "    dbo_Prices = Source{[Schema=\"dbo\",Item=\"Prices\"]}[Data]",
                "in",
                "    dbo_Prices"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Measure 1",
            "expression": "SUM(Prices[Price])"
          }
        ]
      },
      {
        "name": "PropertyType",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "Property Type",
            "dataType": "string",
            "sourceColumn": "Property Type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;PricesPaid\",",
                "    dbo_PropertyType = Source{[Schema=\"dbo\",Item=\"PropertyType\"]}[Data]",
                "in",
                "    dbo_PropertyType"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "95b05e9e-8234-4ee0-95a1-1e0a94cc27bd",
        "fromTable": "Prices",
        "fromColumn": "Business Date ID",
        "toTable": "BusinessDate",
        "toColumn": "ID"
      },
      {
        "name": "b8cd6546-03bc-47ea-9a58-63aaf8c48b3c",
        "fromTable": "Prices",
        "fromColumn": "Location ID",
        "toTable": "Location",
        "toColumn": "ID"
      },
      {
        "name": "0e5763fe-2197-475f-93a0-d06fffc205f2",
        "fromTable": "Prices",
        "fromColumn": "New Build ID",
        "toTable": "NewBuild",
        "toColumn": "ID"
      },
      {
        "name": "10bd7992-aca7-4586-8992-ff58ba05a525",
        "fromTable": "Prices",
        "fromColumn": "Address ID",
        "toTable": "PropertyAddress",
        "toColumn": "ID"
      },
      {
        "name": "7d050625-267b-4219-808d-62eef1211a1e",
        "fromTable": "Prices",
        "fromColumn": "Land Ownership ID",
        "toTable": "LandOwnership",
        "toColumn": "ID"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}